<?php

return [
    'methods' => [
        'baking' => [
            'name' => 'Выпекание',
            'slug' => 'baking',
            'description' => 'Приготовление в духовке',
            'icon' => 'fa-fire',
            'sort_order' => 1,
        ],
        'frying' => [
            'name' => 'Жарка',
            'slug' => 'frying',
            'description' => 'Приготовление на сковороде',
            'icon' => 'fa-fire',
            'sort_order' => 2,
        ],
        'boiling' => [
            'name' => 'Варка',
            'slug' => 'boiling',
            'description' => 'Приготовление в воде',
            'icon' => 'fa-fire',
            'sort_order' => 3,
        ],
        'steaming' => [
            'name' => 'Пар',
            'slug' => 'steaming',
            'description' => 'Приготовление на пару',
            'icon' => 'fa-fire',
            'sort_order' => 4,
        ],
        'grilling' => [
            'name' => 'Гриль',
            'slug' => 'grilling',
            'description' => 'Приготовление на гриле',
            'icon' => 'fa-fire',
            'sort_order' => 5,
        ],
        'slow-cooking' => [
            'name' => 'Медленное приготовление',
            'slug' => 'slow-cooking',
            'description' => 'Приготовление в мультиварке',
            'icon' => 'fa-fire',
            'sort_order' => 6,
        ],
        'pressure-cooking' => [
            'name' => 'Быстрое приготовление',
            'slug' => 'pressure-cooking',
            'description' => 'Приготовление под давлением',
            'icon' => 'fa-fire',
            'sort_order' => 7,
        ],
        'smoking' => [
            'name' => 'Копчение',
            'slug' => 'smoking',
            'description' => 'Приготовление методом копчения',
            'icon' => 'fa-fire',
            'sort_order' => 8,
        ],
        'pickling' => [
            'name' => 'Маринование',
            'slug' => 'pickling',
            'description' => 'Приготовление в маринаде',
            'icon' => 'fa-fire',
            'sort_order' => 9,
        ],
        'fermenting' => [
            'name' => 'Ферментация',
            'slug' => 'fermenting',
            'description' => 'Приготовление методом ферментации',
            'icon' => 'fa-fire',
            'sort_order' => 10,
        ],
        'dehydrating' => [
            'name' => 'Сушка',
            'slug' => 'dehydrating',
            'description' => 'Удаление влаги из продуктов',
            'icon' => 'fa-fire',
            'sort_order' => 11,
        ],
        'freezing' => [
            'name' => 'Заморозка',
            'slug' => 'freezing',
            'description' => 'Приготовление методом заморозки',
            'icon' => 'fa-fire',
            'sort_order' => 12,
        ],
        'canning' => [
            'name' => 'Консервирование',
            'slug' => 'canning',
            'description' => 'Приготовление методом консервирования',
            'icon' => 'fa-fire',
            'sort_order' => 13,
        ],
        'blending' => [
            'name' => 'Измельчение',
            'slug' => 'blending',
            'description' => 'Приготовление в блендере',
            'icon' => 'fa-fire',
            'sort_order' => 14,
        ],
        'juicing' => [
            'name' => 'Соковыжимание',
            'slug' => 'juicing',
            'description' => 'Приготовление соков',
            'icon' => 'fa-fire',
            'sort_order' => 15,
        ],
        'sprouting' => [
            'name' => 'Проращивание',
            'slug' => 'sprouting',
            'description' => 'Приготовление проростков',
            'icon' => 'fa-fire',
            'sort_order' => 16,
        ],
        'aging' => [
            'name' => 'Выдержка',
            'slug' => 'aging',
            'description' => 'Приготовление методом выдержки',
            'icon' => 'fa-fire',
            'sort_order' => 17,
        ],
        'curing' => [
            'name' => 'Вяление',
            'slug' => 'curing',
            'description' => 'Приготовление методом вяления',
            'icon' => 'fa-fire',
            'sort_order' => 18,
        ],
        'braising' => [
            'name' => 'Тушение',
            'slug' => 'braising',
            'description' => 'Приготовление методом тушения',
            'icon' => 'fa-fire',
            'sort_order' => 19,
        ],
        'poaching' => [
            'name' => 'Припускание',
            'slug' => 'poaching',
            'description' => 'Приготовление в горячей жидкости',
            'icon' => 'fa-fire',
            'sort_order' => 20,
        ],
        'sous-vide' => [
            'name' => 'Су-вид',
            'slug' => 'sous-vide',
            'description' => 'Приготовление в вакууме при низкой температуре',
            'icon' => 'fa-fire',
            'sort_order' => 21,
        ],
        'air-frying' => [
            'name' => 'Воздушная жарка',
            'slug' => 'air-frying',
            'description' => 'Приготовление в воздушной фритюрнице',
            'icon' => 'fa-fire',
            'sort_order' => 22,
        ],
        'induction' => [
            'name' => 'Индукция',
            'slug' => 'induction',
            'description' => 'Приготовление на индукционной плите',
            'icon' => 'fa-fire',
            'sort_order' => 23,
        ],
        'microwave' => [
            'name' => 'Микроволновка',
            'slug' => 'microwave',
            'description' => 'Приготовление в микроволновой печи',
            'icon' => 'fa-fire',
            'sort_order' => 24,
        ],
        'toaster-oven' => [
            'name' => 'Тостер-духовка',
            'slug' => 'toaster-oven',
            'description' => 'Приготовление в тостер-духовке',
            'icon' => 'fa-fire',
            'sort_order' => 25,
        ],
        'campfire' => [
            'name' => 'Костер',
            'slug' => 'campfire',
            'description' => 'Приготовление на костре',
            'icon' => 'fa-fire',
            'sort_order' => 26,
        ],
        'solar-cooking' => [
            'name' => 'Солнечная кухня',
            'slug' => 'solar-cooking',
            'description' => 'Приготовление с помощью солнечной энергии',
            'icon' => 'fa-fire',
            'sort_order' => 27,
        ],
        'raw' => [
            'name' => 'Сыроедение',
            'slug' => 'raw',
            'description' => 'Без термической обработки',
            'icon' => 'fa-fire',
            'sort_order' => 28,
        ],
    ],

    'goals' => [
        'weight-gain' => [
            'name' => 'Набор массы',
            'slug' => 'weight-gain',
            'description' => 'Рецепты для набора мышечной массы',
            'icon' => 'fa-arrow-up',
            'sort_order' => 1,
        ],
        'detox' => [
            'name' => 'Детокс',
            'slug' => 'detox',
            'description' => 'Рецепты для очищения организма',
            'icon' => 'fa-leaf',
            'sort_order' => 2,
        ],
        'weight-loss' => [
            'name' => 'Похудение',
            'slug' => 'weight-loss',
            'description' => 'Рецепты для снижения веса',
            'icon' => 'fa-arrow-down',
            'sort_order' => 3,
        ],
        'weight-maintenance' => [
            'name' => 'Поддержка веса',
            'slug' => 'weight-maintenance',
            'description' => 'Рецепты для поддержания веса',
            'icon' => 'fa-balance-scale',
            'sort_order' => 4,
        ],
        'muscle-building' => [
            'name' => 'Набор мышечной массы',
            'slug' => 'muscle-building',
            'description' => 'Рецепты для роста мышц',
            'icon' => 'fa-dumbbell',
            'sort_order' => 5,
        ],
        'endurance' => [
            'name' => 'Выносливость',
            'slug' => 'endurance',
            'description' => 'Рецепты для повышения выносливости',
            'icon' => 'fa-running',
            'sort_order' => 6,
        ],
        'strength' => [
            'name' => 'Сила',
            'slug' => 'strength',
            'description' => 'Рецепты для увеличения силы',
            'icon' => 'fa-fist-raised',
            'sort_order' => 7,
        ],
        'flexibility' => [
            'name' => 'Гибкость',
            'slug' => 'flexibility',
            'description' => 'Рецепты для улучшения гибкости',
            'icon' => 'fa-child',
            'sort_order' => 8,
        ],
        'recovery' => [
            'name' => 'Восстановление',
            'slug' => 'recovery',
            'description' => 'Рецепты для восстановления после тренировок',
            'icon' => 'fa-heart',
            'sort_order' => 9,
        ],
        'pre-workout' => [
            'name' => 'Перед тренировкой',
            'slug' => 'pre-workout',
            'description' => 'Рецепты для приема перед тренировкой',
            'icon' => 'fa-play',
            'sort_order' => 10,
        ],
        'post-workout' => [
            'name' => 'После тренировки',
            'slug' => 'post-workout',
            'description' => 'Рецепты для приема после тренировки',
            'icon' => 'fa-stop',
            'sort_order' => 11,
        ],
        'energy-boost' => [
            'name' => 'Прилив энергии',
            'slug' => 'energy-boost',
            'description' => 'Рецепты для повышения энергии',
            'icon' => 'fa-bolt',
            'sort_order' => 12,
        ],
        'focus' => [
            'name' => 'Концентрация',
            'slug' => 'focus',
            'description' => 'Рецепты для улучшения концентрации',
            'icon' => 'fa-bullseye',
            'sort_order' => 13,
        ],
        'memory' => [
            'name' => 'Память',
            'slug' => 'memory',
            'description' => 'Рецепты для улучшения памяти',
            'icon' => 'fa-brain',
            'sort_order' => 14,
        ],
        'mood' => [
            'name' => 'Настроение',
            'slug' => 'mood',
            'description' => 'Рецепты для улучшения настроения',
            'icon' => 'fa-smile',
            'sort_order' => 15,
        ],
        'stress-relief' => [
            'name' => 'Снятие стресса',
            'slug' => 'stress-relief',
            'description' => 'Рецепты для снятия стресса',
            'icon' => 'fa-peace',
            'sort_order' => 16,
        ],
        'sleep' => [
            'name' => 'Сон',
            'slug' => 'sleep',
            'description' => 'Рецепты для улучшения сна',
            'icon' => 'fa-bed',
            'sort_order' => 17,
        ],
        'digestion' => [
            'name' => 'Пищеварение',
            'slug' => 'digestion',
            'description' => 'Рецепты для улучшения пищеварения',
            'icon' => 'fa-stomach',
            'sort_order' => 18,
        ],
        'immunity' => [
            'name' => 'Иммунитет',
            'slug' => 'immunity',
            'description' => 'Рецепты для укрепления иммунитета',
            'icon' => 'fa-shield-alt',
            'sort_order' => 19,
        ],
        'heart-health' => [
            'name' => 'Здоровье сердца',
            'slug' => 'heart-health',
            'description' => 'Рецепты для здоровья сердечно-сосудистой системы',
            'icon' => 'fa-heartbeat',
            'sort_order' => 20,
        ],
        'bone-health' => [
            'name' => 'Здоровье костей',
            'slug' => 'bone-health',
            'description' => 'Рецепты для укрепления костей',
            'icon' => 'fa-bone',
            'sort_order' => 21,
        ],
        'skin-health' => [
            'name' => 'Здоровье кожи',
            'slug' => 'skin-health',
            'description' => 'Рецепты для здоровья кожи',
            'icon' => 'fa-user',
            'sort_order' => 22,
        ],
        'hair-health' => [
            'name' => 'Здоровье волос',
            'slug' => 'hair-health',
            'description' => 'Рецепты для здоровья волос',
            'icon' => 'fa-cut',
            'sort_order' => 23,
        ],
        'anti-aging' => [
            'name' => 'Антивозрастные',
            'slug' => 'anti-aging',
            'description' => 'Рецепты для замедления старения',
            'icon' => 'fa-clock',
            'sort_order' => 24,
        ],
        'hormone-balance' => [
            'name' => 'Баланс гормонов',
            'slug' => 'hormone-balance',
            'description' => 'Рецепты для баланса гормонов',
            'icon' => 'fa-balance-scale',
            'sort_order' => 25,
        ],
        'thyroid-health' => [
            'name' => 'Здоровье щитовидной железы',
            'slug' => 'thyroid-health',
            'description' => 'Рецепты для здоровья щитовидной железы',
            'icon' => 'fa-heart',
            'sort_order' => 26,
        ],
        'adrenal-health' => [
            'name' => 'Здоровье надпочечников',
            'slug' => 'adrenal-health',
            'description' => 'Рецепты для здоровья надпочечников',
            'icon' => 'fa-heart',
            'sort_order' => 27,
        ],
        'liver-health' => [
            'name' => 'Здоровье печени',
            'slug' => 'liver-health',
            'description' => 'Рецепты для здоровья печени',
            'icon' => 'fa-heart',
            'sort_order' => 28,
        ],
        'kidney-health' => [
            'name' => 'Здоровье почек',
            'slug' => 'kidney-health',
            'description' => 'Рецепты для здоровья почек',
            'icon' => 'fa-heart',
            'sort_order' => 29,
        ],
        'gut-health' => [
            'name' => 'Здоровье кишечника',
            'slug' => 'gut-health',
            'description' => 'Рецепты для здоровья кишечника',
            'icon' => 'fa-heart',
            'sort_order' => 30,
        ],
    ],
];
