<?php

return [
    'types' => [
        'vegetarian' => [
            'name' => 'Вегетарианские',
            'slug' => 'vegetarian',
            'description' => 'Рецепты без мяса и рыбы',
            'color' => '#28a745',
            'sort_order' => 1,
        ],
        'vegan' => [
            'name' => 'Веганские',
            'slug' => 'vegan',
            'description' => 'Рецепты без продуктов животного происхождения',
            'color' => '#20c997',
            'sort_order' => 2,
        ],
        'gluten-free' => [
            'name' => 'Безглютеновые',
            'slug' => 'gluten-free',
            'description' => 'Рецепты без глютена',
            'color' => '#fd7e14',
            'sort_order' => 3,
        ],
        'lactose-free' => [
            'name' => 'Безлактозные',
            'slug' => 'lactose-free',
            'description' => 'Рецепты без лактозы',
            'color' => '#6f42c1',
            'sort_order' => 4,
        ],
        'low-calorie' => [
            'name' => 'Низкокалорийные',
            'slug' => 'low-calorie',
            'description' => 'Рецепты с низким содержанием калорий',
            'color' => '#e83e8c',
            'sort_order' => 5,
        ],
        'high-protein' => [
            'name' => 'Белковые',
            'slug' => 'high-protein',
            'description' => 'Рецепты с высоким содержанием белка',
            'color' => '#007bff',
            'sort_order' => 6,
        ],
        'low-carb' => [
            'name' => 'Низкоуглеводные',
            'slug' => 'low-carb',
            'description' => 'Рецепты с низким содержанием углеводов',
            'color' => '#6c757d',
            'sort_order' => 7,
        ],
        'keto' => [
            'name' => 'Кетогенные',
            'slug' => 'keto',
            'description' => 'Рецепты для кетогенной диеты',
            'color' => '#17a2b8',
            'sort_order' => 8,
        ],
        'paleo' => [
            'name' => 'Палео',
            'slug' => 'paleo',
            'description' => 'Рецепты палеолитической диеты',
            'color' => '#8b4513',
            'sort_order' => 9,
        ],
        'mediterranean' => [
            'name' => 'Средиземноморские',
            'slug' => 'mediterranean',
            'description' => 'Рецепты средиземноморской диеты',
            'color' => '#007bff',
            'sort_order' => 10,
        ],
        'dash' => [
            'name' => 'DASH диета',
            'slug' => 'dash',
            'description' => 'Рецепты для снижения давления',
            'color' => '#6f42c1',
            'sort_order' => 11,
        ],
        'low-fat' => [
            'name' => 'Низкожировые',
            'slug' => 'low-fat',
            'description' => 'Рецепты с низким содержанием жиров',
            'color' => '#28a745',
            'sort_order' => 12,
        ],
        'high-fiber' => [
            'name' => 'Высоковолокнистые',
            'slug' => 'high-fiber',
            'description' => 'Рецепты с высоким содержанием клетчатки',
            'color' => '#20c997',
            'sort_order' => 13,
        ],
        'anti-inflammatory' => [
            'name' => 'Противовоспалительные',
            'slug' => 'anti-inflammatory',
            'description' => 'Рецепты для уменьшения воспаления',
            'color' => '#fd7e14',
            'sort_order' => 14,
        ],
        'diabetic-friendly' => [
            'name' => 'Для диабетиков',
            'slug' => 'diabetic-friendly',
            'description' => 'Рецепты подходящие для диабетиков',
            'color' => '#e83e8c',
            'sort_order' => 15,
        ],
        'heart-healthy' => [
            'name' => 'Для сердца',
            'slug' => 'heart-healthy',
            'description' => 'Рецепты полезные для сердечно-сосудистой системы',
            'color' => '#dc3545',
            'sort_order' => 16,
        ],
        'gut-healthy' => [
            'name' => 'Для кишечника',
            'slug' => 'gut-healthy',
            'description' => 'Рецепты полезные для пищеварения',
            'color' => '#6c757d',
            'sort_order' => 17,
        ],
        'immune-boosting' => [
            'name' => 'Иммуностимулирующие',
            'slug' => 'immune-boosting',
            'description' => 'Рецепты для укрепления иммунитета',
            'color' => '#ffc107',
            'sort_order' => 18,
        ],
        'energy-boosting' => [
            'name' => 'Энергетические',
            'slug' => 'energy-boosting',
            'description' => 'Рецепты для повышения энергии',
            'color' => '#fd7e14',
            'sort_order' => 19,
        ],
        'sleep-friendly' => [
            'name' => 'Для сна',
            'slug' => 'sleep-friendly',
            'description' => 'Рецепты способствующие хорошему сну',
            'color' => '#6f42c1',
            'sort_order' => 20,
        ],
        'brain-boosting' => [
            'name' => 'Для мозга',
            'slug' => 'brain-boosting',
            'description' => 'Рецепты для улучшения работы мозга',
            'color' => '#17a2b8',
            'sort_order' => 21,
        ],
        'bone-healthy' => [
            'name' => 'Для костей',
            'slug' => 'bone-healthy',
            'description' => 'Рецепты для укрепления костей',
            'color' => '#8b4513',
            'sort_order' => 22,
        ],
        'skin-healthy' => [
            'name' => 'Для кожи',
            'slug' => 'skin-healthy',
            'description' => 'Рецепты для здоровья кожи',
            'color' => '#e83e8c',
            'sort_order' => 23,
        ],
        'hair-healthy' => [
            'name' => 'Для волос',
            'slug' => 'hair-healthy',
            'description' => 'Рецепты для здоровья волос',
            'color' => '#6c757d',
            'sort_order' => 24,
        ],
        'detox' => [
            'name' => 'Детокс',
            'slug' => 'detox',
            'description' => 'Рецепты для очищения организма',
            'color' => '#28a745',
            'sort_order' => 25,
        ],
        'alkaline' => [
            'name' => 'Щелочные',
            'slug' => 'alkaline',
            'description' => 'Рецепты щелочной диеты',
            'color' => '#20c997',
            'sort_order' => 26,
        ],
        'raw-food' => [
            'name' => 'Сыроедение',
            'slug' => 'raw-food',
            'description' => 'Рецепты без термической обработки',
            'color' => '#fd7e14',
            'sort_order' => 27,
        ],
        'intermittent-fasting' => [
            'name' => 'Интервальное голодание',
            'slug' => 'intermittent-fasting',
            'description' => 'Рецепты для интервального голодания',
            'color' => '#6f42c1',
            'sort_order' => 28,
        ],
        'portion-control' => [
            'name' => 'Контроль порций',
            'slug' => 'portion-control',
            'description' => 'Рецепты с контролируемыми порциями',
            'color' => '#e83e8c',
            'sort_order' => 29,
        ],
        'mindful-eating' => [
            'name' => 'Осознанное питание',
            'slug' => 'mindful-eating',
            'description' => 'Рецепты для осознанного питания',
            'color' => '#17a2b8',
            'sort_order' => 30,
        ],
    ],
];
