<?php

return [
    'meal_types' => [
        'breakfast' => [
            'name' => 'Завтрак',
            'slug' => 'breakfast',
            'description' => 'Утренние блюда',
            'icon' => 'fa-sun',
            'sort_order' => 1,
        ],
        'brunch' => [
            'name' => 'Бранч',
            'slug' => 'brunch',
            'description' => 'Поздний завтрак',
            'icon' => 'fa-coffee',
            'sort_order' => 2,
        ],
        'morning-snack' => [
            'name' => 'Утренний перекус',
            'slug' => 'morning-snack',
            'description' => 'Легкий перекус между завтраком и обедом',
            'icon' => 'fa-apple-alt',
            'sort_order' => 3,
        ],
        'lunch' => [
            'name' => 'Обед',
            'slug' => 'lunch',
            'description' => 'Дневные блюда',
            'icon' => 'fa-utensils',
            'sort_order' => 4,
        ],
        'afternoon-snack' => [
            'name' => 'Дневной перекус',
            'slug' => 'afternoon-snack',
            'description' => 'Перекус между обедом и ужином',
            'icon' => 'fa-apple-alt',
            'sort_order' => 5,
        ],
        'dinner' => [
            'name' => 'Ужин',
            'slug' => 'dinner',
            'description' => 'Вечерние блюда',
            'icon' => 'fa-moon',
            'sort_order' => 6,
        ],
        'evening-snack' => [
            'name' => 'Вечерний перекус',
            'slug' => 'evening-snack',
            'description' => 'Легкий перекус перед сном',
            'icon' => 'fa-apple-alt',
            'sort_order' => 7,
        ],
        'dessert' => [
            'name' => 'Десерт',
            'slug' => 'dessert',
            'description' => 'Сладкие блюда',
            'icon' => 'fa-ice-cream',
            'sort_order' => 8,
        ],
        'appetizer' => [
            'name' => 'Закуска',
            'slug' => 'appetizer',
            'description' => 'Легкие закуски',
            'icon' => 'fa-cheese',
            'sort_order' => 9,
        ],
        'soup' => [
            'name' => 'Супы',
            'slug' => 'soup',
            'description' => 'Первые блюда',
            'icon' => 'fa-mug-hot',
            'sort_order' => 10,
        ],
        'salad' => [
            'name' => 'Салаты',
            'slug' => 'salad',
            'description' => 'Свежие салаты',
            'icon' => 'fa-leaf',
            'sort_order' => 11,
        ],
        'main-course' => [
            'name' => 'Основное блюдо',
            'slug' => 'main-course',
            'description' => 'Главные блюда',
            'icon' => 'fa-drumstick-bite',
            'sort_order' => 12,
        ],
        'side-dish' => [
            'name' => 'Гарнир',
            'slug' => 'side-dish',
            'description' => 'Дополнительные блюда',
            'icon' => 'fa-carrot',
            'sort_order' => 13,
        ],
        'beverage' => [
            'name' => 'Напитки',
            'slug' => 'beverage',
            'description' => 'Различные напитки',
            'icon' => 'fa-glass-whiskey',
            'sort_order' => 14,
        ],
        'smoothie' => [
            'name' => 'Смузи',
            'slug' => 'smoothie',
            'description' => 'Питательные смузи',
            'icon' => 'fa-glass-whiskey',
            'sort_order' => 15,
        ],
        'juice' => [
            'name' => 'Соки',
            'slug' => 'juice',
            'description' => 'Свежевыжатые соки',
            'icon' => 'fa-glass-whiskey',
            'sort_order' => 16,
        ],
        'tea' => [
            'name' => 'Чай',
            'slug' => 'tea',
            'description' => 'Различные виды чая',
            'icon' => 'fa-glass-whiskey',
            'sort_order' => 17,
        ],
        'coffee' => [
            'name' => 'Кофе',
            'slug' => 'coffee',
            'description' => 'Кофейные напитки',
            'icon' => 'fa-glass-whiskey',
            'sort_order' => 18,
        ],
        'protein-shake' => [
            'name' => 'Протеиновый коктейль',
            'slug' => 'protein-shake',
            'description' => 'Белковые коктейли',
            'icon' => 'fa-glass-whiskey',
            'sort_order' => 19,
        ],
        'energy-bar' => [
            'name' => 'Энергетический батончик',
            'slug' => 'energy-bar',
            'description' => 'Домашние энергетические батончики',
            'icon' => 'fa-cookie-bite',
            'sort_order' => 20,
        ],
        'granola' => [
            'name' => 'Гранола',
            'slug' => 'granola',
            'description' => 'Домашняя гранола',
            'icon' => 'fa-cookie-bite',
            'sort_order' => 21,
        ],
        'yogurt' => [
            'name' => 'Йогурт',
            'slug' => 'yogurt',
            'description' => 'Домашний йогурт',
            'icon' => 'fa-cheese',
            'sort_order' => 22,
        ],
        'kefir' => [
            'name' => 'Кефир',
            'slug' => 'kefir',
            'description' => 'Домашний кефир',
            'icon' => 'fa-glass-whiskey',
            'sort_order' => 23,
        ],
        'kombucha' => [
            'name' => 'Комбуча',
            'slug' => 'kombucha',
            'description' => 'Домашняя комбуча',
            'icon' => 'fa-glass-whiskey',
            'sort_order' => 24,
        ],
    ],

    'seasons' => [
        'spring' => [
            'name' => 'Весна',
            'slug' => 'spring',
            'description' => 'Весенние блюда',
            'color' => '#28a745',
            'sort_order' => 1,
        ],
        'summer' => [
            'name' => 'Лето',
            'slug' => 'summer',
            'description' => 'Летние блюда',
            'color' => '#ffc107',
            'sort_order' => 2,
        ],
        'autumn' => [
            'name' => 'Осень',
            'slug' => 'autumn',
            'description' => 'Осенние блюда',
            'color' => '#fd7e14',
            'sort_order' => 3,
        ],
        'winter' => [
            'name' => 'Зима',
            'slug' => 'winter',
            'description' => 'Зимние блюда',
            'color' => '#6c757d',
            'sort_order' => 4,
        ],
        'all-year' => [
            'name' => 'Круглый год',
            'slug' => 'all-year',
            'description' => 'Блюда для любого времени года',
            'color' => '#007bff',
            'sort_order' => 5,
        ],
    ],

    'cuisines' => [
        'russian' => [
            'name' => 'Русская кухня',
            'slug' => 'russian',
            'description' => 'Традиционные русские блюда',
            'color' => '#dc3545',
            'sort_order' => 1,
        ],
        'italian' => [
            'name' => 'Итальянская кухня',
            'slug' => 'italian',
            'description' => 'Классические итальянские блюда',
            'color' => '#28a745',
            'sort_order' => 2,
        ],
        'mediterranean' => [
            'name' => 'Средиземноморская кухня',
            'slug' => 'mediterranean',
            'description' => 'Здоровые блюда Средиземноморья',
            'color' => '#007bff',
            'sort_order' => 3,
        ],
        'asian' => [
            'name' => 'Азиатская кухня',
            'slug' => 'asian',
            'description' => 'Блюда стран Азии',
            'color' => '#fd7e14',
            'sort_order' => 4,
        ],
        'mexican' => [
            'name' => 'Мексиканская кухня',
            'slug' => 'mexican',
            'description' => 'Острые мексиканские блюда',
            'color' => '#ffc107',
            'sort_order' => 5,
        ],
        'indian' => [
            'name' => 'Индийская кухня',
            'slug' => 'indian',
            'description' => 'Ароматные индийские блюда',
            'color' => '#6f42c1',
            'sort_order' => 6,
        ],
        'french' => [
            'name' => 'Французская кухня',
            'slug' => 'french',
            'description' => 'Изысканная французская кухня',
            'color' => '#e83e8c',
            'sort_order' => 7,
        ],
        'greek' => [
            'name' => 'Греческая кухня',
            'slug' => 'greek',
            'description' => 'Традиционная греческая кухня',
            'color' => '#20c997',
            'sort_order' => 8,
        ],
        'thai' => [
            'name' => 'Тайская кухня',
            'slug' => 'thai',
            'description' => 'Острая тайская кухня',
            'color' => '#fd7e14',
            'sort_order' => 9,
        ],
        'japanese' => [
            'name' => 'Японская кухня',
            'slug' => 'japanese',
            'description' => 'Традиционная японская кухня',
            'color' => '#dc3545',
            'sort_order' => 10,
        ],
        'chinese' => [
            'name' => 'Китайская кухня',
            'slug' => 'chinese',
            'description' => 'Традиционная китайская кухня',
            'color' => '#dc3545',
            'sort_order' => 11,
        ],
        'korean' => [
            'name' => 'Корейская кухня',
            'slug' => 'korean',
            'description' => 'Традиционная корейская кухня',
            'color' => '#dc3545',
            'sort_order' => 12,
        ],
        'vietnamese' => [
            'name' => 'Вьетнамская кухня',
            'slug' => 'vietnamese',
            'description' => 'Традиционная вьетнамская кухня',
            'color' => '#dc3545',
            'sort_order' => 13,
        ],
        'lebanese' => [
            'name' => 'Ливанская кухня',
            'slug' => 'lebanese',
            'description' => 'Традиционная ливанская кухня',
            'color' => '#dc3545',
            'sort_order' => 14,
        ],
        'turkish' => [
            'name' => 'Турецкая кухня',
            'slug' => 'turkish',
            'description' => 'Традиционная турецкая кухня',
            'color' => '#dc3545',
            'sort_order' => 15,
        ],
        'moroccan' => [
            'name' => 'Марокканская кухня',
            'slug' => 'moroccan',
            'description' => 'Традиционная марокканская кухня',
            'color' => '#dc3545',
            'sort_order' => 16,
        ],
        'ethiopian' => [
            'name' => 'Эфиопская кухня',
            'slug' => 'ethiopian',
            'description' => 'Традиционная эфиопская кухня',
            'color' => '#dc3545',
            'sort_order' => 17,
        ],
        'brazilian' => [
            'name' => 'Бразильская кухня',
            'slug' => 'brazilian',
            'description' => 'Традиционная бразильская кухня',
            'color' => '#dc3545',
            'sort_order' => 18,
        ],
        'peruvian' => [
            'name' => 'Перуанская кухня',
            'slug' => 'peruvian',
            'description' => 'Традиционная перуанская кухня',
            'color' => '#dc3545',
            'sort_order' => 19,
        ],
        'caribbean' => [
            'name' => 'Карибская кухня',
            'slug' => 'caribbean',
            'description' => 'Традиционная карибская кухня',
            'color' => '#dc3545',
            'sort_order' => 20,
        ],
    ],

    'defaults' => [
        'nutrition' => [
            'calories' => 2000,
            'protein' => 150,
            'fat' => 65,
            'carbs' => 250,
        ],
        'meals_per_day' => 5,
        'snacks_per_day' => 2,
    ],

    'subscription_levels' => [
        'basic' => [
            'name' => 'Базовый',
            'description' => 'Базовые планы питания',
            'features' => ['basic_plans', 'standard_recipes'],
        ],
        'optimal' => [
            'name' => 'Оптимальный',
            'description' => 'Расширенные планы питания',
            'features' => ['basic_plans', 'standard_recipes', 'premium_recipes', 'customization'],
        ],
        'premium' => [
            'name' => 'Премиум',
            'description' => 'Полные планы питания с персонализацией',
            'features' => ['basic_plans', 'standard_recipes', 'premium_recipes', 'customization', 'personal_coach', 'ai_recommendations'],
        ],
    ],

    'plan_durations' => [
        '1_day' => [
            'name' => '1 день',
            'days' => 1,
            'description' => 'План питания на один день',
        ],
        '3_days' => [
            'name' => '3 дня',
            'days' => 3,
            'description' => 'План питания на три дня',
        ],
        '7_days' => [
            'name' => '1 неделя',
            'days' => 7,
            'description' => 'План питания на неделю',
        ],
        '14_days' => [
            'name' => '2 недели',
            'days' => 14,
            'description' => 'План питания на две недели',
        ],
        '30_days' => [
            'name' => '1 месяц',
            'days' => 30,
            'description' => 'План питания на месяц',
        ],
        '90_days' => [
            'name' => '3 месяца',
            'days' => 90,
            'description' => 'План питания на три месяца',
        ],
    ],
];
