<?php

return [
    'plans' => [
        'free' => [
            'name' => 'Бесплатный',
            'slug' => 'free',
            'description' => 'Базовый доступ к системе',
            'price' => 0,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => false,
                'nutrition_calculator' => false,
                'personalization' => false,
                'ai_recommendations' => false,
                'personal_coach' => false,
                'premium_recipes' => false,
                'exclusive_content' => false,
                'community_access' => false,
                'mobile_app' => false,
                'offline_access' => false,
                'priority_support' => false,
                'workshop_access' => false,
                'recipe_creation' => false,
                'shopping_lists' => false,
                'meal_tracking' => false,
                'progress_analytics' => false,
                'social_features' => false,
                'export_data' => false,
                'api_access' => false,
            ],
            'sort_order' => 1,
        ],
        'basic' => [
            'name' => 'Базовый',
            'slug' => 'basic',
            'description' => 'Основной доступ к рецептам и базовым функциям',
            'price' => 299,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => true,
                'nutrition_calculator' => true,
                'personalization' => false,
                'ai_recommendations' => false,
                'personal_coach' => false,
                'premium_recipes' => false,
                'exclusive_content' => false,
                'community_access' => false,
                'mobile_app' => true,
                'offline_access' => false,
                'priority_support' => false,
                'workshop_access' => false,
                'recipe_creation' => false,
                'shopping_lists' => true,
                'meal_tracking' => true,
                'progress_analytics' => false,
                'social_features' => false,
                'export_data' => false,
                'api_access' => false,
            ],
            'sort_order' => 2,
        ],
        'optimal' => [
            'name' => 'Оптимальный',
            'slug' => 'optimal',
            'description' => 'Расширенный доступ с персонализацией и AI рекомендациями',
            'price' => 599,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => true,
                'nutrition_calculator' => true,
                'personalization' => true,
                'ai_recommendations' => true,
                'personal_coach' => false,
                'premium_recipes' => true,
                'exclusive_content' => true,
                'community_access' => true,
                'mobile_app' => true,
                'offline_access' => true,
                'priority_support' => true,
                'workshop_access' => true,
                'recipe_creation' => true,
                'shopping_lists' => true,
                'meal_tracking' => true,
                'progress_analytics' => true,
                'social_features' => true,
                'export_data' => true,
                'api_access' => false,
            ],
            'sort_order' => 3,
        ],
        'premium' => [
            'name' => 'Премиум',
            'slug' => 'premium',
            'description' => 'Полный доступ с персональным коучем и эксклюзивным контентом',
            'price' => 1299,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => true,
                'nutrition_calculator' => true,
                'personalization' => true,
                'ai_recommendations' => true,
                'personal_coach' => true,
                'premium_recipes' => true,
                'exclusive_content' => true,
                'community_access' => true,
                'mobile_app' => true,
                'offline_access' => true,
                'priority_support' => true,
                'workshop_access' => true,
                'recipe_creation' => true,
                'shopping_lists' => true,
                'meal_tracking' => true,
                'progress_analytics' => true,
                'social_features' => true,
                'export_data' => true,
                'api_access' => true,
            ],
            'sort_order' => 4,
        ],
        'family' => [
            'name' => 'Семейный',
            'slug' => 'family',
            'description' => 'Доступ для всей семьи с детскими рецептами',
            'price' => 899,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => true,
                'nutrition_calculator' => true,
                'personalization' => true,
                'ai_recommendations' => true,
                'personal_coach' => false,
                'premium_recipes' => true,
                'exclusive_content' => true,
                'community_access' => true,
                'mobile_app' => true,
                'offline_access' => true,
                'priority_support' => true,
                'workshop_access' => true,
                'recipe_creation' => true,
                'shopping_lists' => true,
                'meal_tracking' => true,
                'progress_analytics' => true,
                'social_features' => true,
                'export_data' => true,
                'api_access' => false,
                'family_accounts' => true,
                'kids_recipes' => true,
                'allergy_tracking' => true,
            ],
            'sort_order' => 5,
        ],
        'athlete' => [
            'name' => 'Спортсмен',
            'slug' => 'athlete',
            'description' => 'Специализированные планы для спортсменов',
            'price' => 999,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => true,
                'nutrition_calculator' => true,
                'personalization' => true,
                'ai_recommendations' => true,
                'personal_coach' => true,
                'premium_recipes' => true,
                'exclusive_content' => true,
                'community_access' => true,
                'mobile_app' => true,
                'offline_access' => true,
                'priority_support' => true,
                'workshop_access' => true,
                'recipe_creation' => true,
                'shopping_lists' => true,
                'meal_tracking' => true,
                'progress_analytics' => true,
                'social_features' => true,
                'export_data' => true,
                'api_access' => true,
                'sports_nutrition' => true,
                'workout_integration' => true,
                'performance_tracking' => true,
            ],
            'sort_order' => 6,
        ],
        'diabetic' => [
            'name' => 'Диабетик',
            'slug' => 'diabetic',
            'description' => 'Специализированные планы для диабетиков',
            'price' => 799,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => true,
                'nutrition_calculator' => true,
                'personalization' => true,
                'ai_recommendations' => true,
                'personal_coach' => false,
                'premium_recipes' => true,
                'exclusive_content' => true,
                'community_access' => true,
                'mobile_app' => true,
                'offline_access' => true,
                'priority_support' => true,
                'workshop_access' => true,
                'recipe_creation' => true,
                'shopping_lists' => true,
                'meal_tracking' => true,
                'progress_analytics' => true,
                'social_features' => true,
                'export_data' => true,
                'api_access' => false,
                'diabetic_recipes' => true,
                'blood_sugar_tracking' => true,
                'medical_integration' => true,
            ],
            'sort_order' => 7,
        ],
        'weight-loss' => [
            'name' => 'Похудение',
            'slug' => 'weight-loss',
            'description' => 'Специализированные планы для похудения',
            'price' => 699,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => true,
                'nutrition_calculator' => true,
                'personalization' => true,
                'ai_recommendations' => true,
                'personal_coach' => false,
                'premium_recipes' => true,
                'exclusive_content' => true,
                'community_access' => true,
                'mobile_app' => true,
                'offline_access' => true,
                'priority_support' => true,
                'workshop_access' => true,
                'recipe_creation' => true,
                'shopping_lists' => true,
                'meal_tracking' => true,
                'progress_analytics' => true,
                'social_features' => true,
                'export_data' => true,
                'api_access' => false,
                'weight_tracking' => true,
                'calorie_deficit_calculator' => true,
                'motivation_tools' => true,
            ],
            'sort_order' => 8,
        ],
        'keto' => [
            'name' => 'Кето',
            'slug' => 'keto',
            'description' => 'Специализированные кетогенные планы',
            'price' => 749,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => true,
                'nutrition_calculator' => true,
                'personalization' => true,
                'ai_recommendations' => true,
                'personal_coach' => false,
                'premium_recipes' => true,
                'exclusive_content' => true,
                'community_access' => true,
                'mobile_app' => true,
                'offline_access' => true,
                'priority_support' => true,
                'workshop_access' => true,
                'recipe_creation' => true,
                'shopping_lists' => true,
                'meal_tracking' => true,
                'progress_analytics' => true,
                'social_features' => true,
                'export_data' => true,
                'api_access' => false,
                'keto_recipes' => true,
                'ketone_tracking' => true,
                'macro_calculator' => true,
            ],
            'sort_order' => 9,
        ],
        'vegan' => [
            'name' => 'Веган',
            'slug' => 'vegan',
            'description' => 'Специализированные веганские планы',
            'price' => 649,
            'currency' => 'RUB',
            'billing_period' => 'monthly',
            'features' => [
                'basic_recipes' => true,
                'meal_plans' => true,
                'nutrition_calculator' => true,
                'personalization' => true,
                'ai_recommendations' => true,
                'personal_coach' => false,
                'premium_recipes' => true,
                'exclusive_content' => true,
                'community_access' => true,
                'mobile_app' => true,
                'offline_access' => true,
                'priority_support' => true,
                'workshop_access' => true,
                'recipe_creation' => true,
                'shopping_lists' => true,
                'meal_tracking' => true,
                'progress_analytics' => true,
                'social_features' => true,
                'export_data' => true,
                'api_access' => false,
                'vegan_recipes' => true,
                'protein_tracking' => true,
                'supplement_guide' => true,
            ],
            'sort_order' => 10,
        ],
    ],

    'billing_periods' => [
        'monthly' => [
            'name' => 'Ежемесячно',
            'slug' => 'monthly',
            'months' => 1,
            'discount' => 0,
        ],
        'quarterly' => [
            'name' => 'Ежеквартально',
            'slug' => 'quarterly',
            'months' => 3,
            'discount' => 10,
        ],
        'semi_annually' => [
            'name' => 'Полугодично',
            'slug' => 'semi_annually',
            'months' => 6,
            'discount' => 20,
        ],
        'annually' => [
            'name' => 'Ежегодно',
            'slug' => 'annually',
            'months' => 12,
            'discount' => 30,
        ],
        'biennially' => [
            'name' => 'Раз в 2 года',
            'slug' => 'biennially',
            'months' => 24,
            'discount' => 40,
        ],
    ],

    'currencies' => [
        'RUB' => [
            'name' => 'Российский рубль',
            'symbol' => '₽',
            'code' => 'RUB',
        ],
        'USD' => [
            'name' => 'Доллар США',
            'symbol' => '$',
            'code' => 'USD',
        ],
        'EUR' => [
            'name' => 'Евро',
            'symbol' => '€',
            'code' => 'EUR',
        ],
        'GBP' => [
            'name' => 'Фунт стерлингов',
            'symbol' => '£',
            'code' => 'GBP',
        ],
    ],

    'features' => [
        'basic_recipes' => 'Базовые рецепты',
        'meal_plans' => 'Планы питания',
        'nutrition_calculator' => 'Калькулятор питания',
        'personalization' => 'Персонализация',
        'ai_recommendations' => 'AI рекомендации',
        'personal_coach' => 'Персональный коуч',
        'premium_recipes' => 'Премиум рецепты',
        'exclusive_content' => 'Эксклюзивный контент',
        'community_access' => 'Доступ к сообществу',
        'mobile_app' => 'Мобильное приложение',
        'offline_access' => 'Офлайн доступ',
        'priority_support' => 'Приоритетная поддержка',
        'workshop_access' => 'Доступ к мастер-классам',
        'recipe_creation' => 'Создание рецептов',
        'shopping_lists' => 'Списки покупок',
        'meal_tracking' => 'Отслеживание приемов пищи',
        'progress_analytics' => 'Аналитика прогресса',
        'social_features' => 'Социальные функции',
        'export_data' => 'Экспорт данных',
        'api_access' => 'Доступ к API',
        'family_accounts' => 'Семейные аккаунты',
        'kids_recipes' => 'Детские рецепты',
        'allergy_tracking' => 'Отслеживание аллергий',
        'sports_nutrition' => 'Спортивное питание',
        'workout_integration' => 'Интеграция с тренировками',
        'performance_tracking' => 'Отслеживание производительности',
        'diabetic_recipes' => 'Рецепты для диабетиков',
        'blood_sugar_tracking' => 'Отслеживание сахара в крови',
        'medical_integration' => 'Медицинская интеграция',
        'weight_tracking' => 'Отслеживание веса',
        'calorie_deficit_calculator' => 'Калькулятор дефицита калорий',
        'motivation_tools' => 'Инструменты мотивации',
        'keto_recipes' => 'Кетогенные рецепты',
        'ketone_tracking' => 'Отслеживание кетонов',
        'macro_calculator' => 'Калькулятор макронутриентов',
        'vegan_recipes' => 'Веганские рецепты',
        'protein_tracking' => 'Отслеживание белка',
        'supplement_guide' => 'Руководство по добавкам',
    ],

    'payment_methods' => [
        'credit_card' => [
            'name' => 'Кредитная карта',
            'icon' => 'fa-credit-card',
        ],
        'debit_card' => [
            'name' => 'Дебетовая карта',
            'icon' => 'fa-credit-card',
        ],
        'paypal' => [
            'name' => 'PayPal',
            'icon' => 'fa-paypal',
        ],
        'apple_pay' => [
            'name' => 'Apple Pay',
            'icon' => 'fa-apple',
        ],
        'google_pay' => [
            'name' => 'Google Pay',
            'icon' => 'fa-google',
        ],
        'bank_transfer' => [
            'name' => 'Банковский перевод',
            'icon' => 'fa-university',
        ],
        'crypto' => [
            'name' => 'Криптовалюта',
            'icon' => 'fa-bitcoin',
        ],
    ],
];
